### ISSUE TITLE
Rev. 1.7 CH340E

### ISSUE THREAD

**Issue by Titanius** [egony/MODKAM-STICK-V3#1]
Hello, I finished Rev 1.7 with CH340E. When I connect it to USB I don't get a USB device displayed. Isn't it so that a USB device has to be displayed?

**Comment by egony** [comment]
A COM port should appear in the Device Manager.

**Comment by Titanius** [comment]
did you test rev 1.7 with ch340e on yourself?  Is that okay with the 33 ohm resistors?  None are mentioned in the datasheet.  
Can't the chip withstand high temperatures when soldering by hand?
And the com port is also displayed regardless of the state of the cc2538?

**Comment by egony** [comment]
Yes, I have tested. Where do you think the photos come from? I tested it with 33 ohm resistors. But it is more correct to put a jumper or a 0 ohm resistor.
ch340e chip can be easily damaged by high temperatures.
The COM port should be detected even without 2538.

**Comment by Titanius** [comment]
OK Thank you. i think the temperature was too high and it was damaged

**Comment by egony** [comment]
You can remove ch340 and resolder board to classic v3 layout. Any way you need j-link programmer for first flashing.
